import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import I18nProvider from "../components/I18nProvider";
import Header from "../components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <I18nProvider>
          <Header />
          {children}
          {/* 1x1 tracking pixel to log IP without JS */}
          <img
            src="https://backend-gydk.onrender.com/api/pixel?path=/"
            alt=""
            width="1"
            height="1"
            style={{ position: "absolute", left: "-9999px" }}
          />
        </I18nProvider>
      </body>
    </html>
  );
}